name = "asynchrony"
uuid = "7ad9d156-05cf-4bad-89c3-9ea3c8e19026"
authors = ["Michael E. DeWitt <me.dewitt.jr@gmail.com>", "Nicholas Kortessis"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
